INSERT INTO project (name) VALUES ('Project#1')
INSERT INTO project (name) VALUES ('Project#2')
INSERT INTO project (name) VALUES ('Project#3')
INSERT INTO project (name) VALUES ('Project#4')
INSERT INTO project (name) VALUES ('Project#5')
INSERT INTO project (name) VALUES ('Project#6')
INSERT INTO project (name) VALUES ('Project#7')
INSERT INTO project (name) VALUES ('Project#8')
INSERT INTO project (name) VALUES ('Project#9')

INSERT INTO scanned_dependency_list (dependencies) VALUES ('org.projectlombok/lombok, org.springframework.boot/spring-boot-starter-security, com.h2database/h2')
INSERT INTO scanned_dependency_list (dependencies) VALUES ('org.projectlombok/lombok, org.springframework.boot/spring-boot-starter-security, com.h2database/h2')
INSERT INTO scanned_dependency_list (dependencies) VALUES ('org.projectlombok/lombok, org.springframework.boot/spring-boot-starter-security, com.h2database/h2')
INSERT INTO scanned_dependency_list (dependencies) VALUES ('org.projectlombok/lombok, org.springframework.boot/spring-boot-starter-security, com.h2database/h2')
INSERT INTO scanned_dependency_list (dependencies) VALUES ('org.projectlombok/lombok, org.springframework.boot/spring-boot-starter-security, com.h2database/h2')
INSERT INTO scanned_dependency_list (dependencies) VALUES ('org.projectlombok/lombok, org.springframework.boot/spring-boot-starter-security, com.h2database/h2')
INSERT INTO scanned_dependency_list (dependencies) VALUES ('org.projectlombok/lombok, org.springframework.boot/spring-boot-starter-security, com.h2database/h2')
INSERT INTO scanned_dependency_list (dependencies) VALUES ('org.projectlombok/lombok, org.springframework.boot/spring-boot-starter-security, com.h2database/h2')
INSERT INTO scanned_dependency_list (dependencies) VALUES ('org.projectlombok/lombok, org.springframework.boot/spring-boot-starter-security, com.h2database/h2')
INSERT INTO scanned_dependency_list (dependencies) VALUES ('org.projectlombok/lombok, org.springframework.boot/spring-boot-starter-security, com.h2database/h2')
